"""Added Team model

Revision ID: b770931f9baf
Revises: c6a6aadd63cc
Create Date: 2025-08-26 20:08:40.097542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b770931f9baf'
down_revision: Union[str, None] = 'c6a6aadd63cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('First_name', sa.String(length=20), nullable=True),
    sa.Column('Last_name', sa.String(length=20), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Height', sa.String(), nullable=True),
    sa.Column('Position', sa.String(), nullable=True),
    sa.Column('Jersey_Numbet', sa.Integer(), nullable=True),
    sa.Column('Signing_Date', sa.DateTime(), nullable=True),
    sa.Column('Team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
