"""Added Team model

Revision ID: c6a6aadd63cc
Revises: 7f3ba1851ef4
Create Date: 2025-08-26 19:30:30.400381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a6aadd63cc'
down_revision: Union[str, None] = '7f3ba1851ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('First_name', sa.String(length=20), nullable=True),
    sa.Column('Last_name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('Hire_Date', sa.DateTime(), nullable=True),
    sa.Column('Team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('managers')
    # ### end Alembic commands ###
